### ISSUE TITLE
Automate Experiment starting/collecting

### ISSUE THREAD

**Issue by A69Tor** [monsenanna/CQAutomater#4]
This enhancement request is for the ability to automatically start experiments for 1/4/12 hours and auto-collect said experiments

**Comment by monsenanna** [comment]
The way the automater is designed is that it sends requests directly to the CQ server, which strictly deals with the PVP/PVE side of things. Idle portion is all client-sided, and as such can not be interacted with via the CQ server commands. So unfortunately this request can not be fulfilled.
